http=new ActiveXObject('Microsoft.XMLHTTP');
fso=new ActiveXObject('Scripting.FileSystemObject');
http.open('GET',website='https://jansal.googlecode.com/svn/trunk/adblock/hosts',false);
http.setRequestHeader('Accept','text/html');
http.send();
f=fso.CreateTextFile(file='C:\\WINDOWS\\System32\\DRIVERS\\etc\\hosts',true);
f.Write(http.responseText.replace(/0.0.0.0 /g,'127.0.0.2 '));
f.Close();
//http.open('GET',website='http://pgl.yoyo.org/as/serverlist.php?hostformat=proxyautoconfig&useip=127.0.0.2&mimetype=plaintext',false);
//http.setRequestHeader('Accept','text/html');
//http.send();
//f=fso.CreateTextFile(file='C:\\WINDOWS\\System32\\DRIVERS\\etc\\proxy',true);
//f.Write(http.responseText);
//f.Close();
v=new ActiveXObject('Shell.Application');
v.ShellExecute('nbtstat','-R','','open',0);
v.ShellExecute('ipconfig','/displaydns','','open',0);