http=new ActiveXObject("Microsoft.XMLHTTP");
fso=new ActiveXObject("Scripting.FileSystemObject");
f=fso.CreateTextFile(file="hostperm.txt",true);
http.open("GET", website="http://pgl.yoyo.org/as/serverlist.php?hostformat=hostperm.1&showintro=0&mimetype=plaintext", false);
http.setRequestHeader("Accept","text/html");
http.send();
f.Write(http.responseText.replace(/host\timage\t2\t/g,""));
//http.open("GET", website="http://mirror1.malwaredomains.com/files/justdomains", false);
//http.setRequestHeader("Accept","text/html");
//http.send();
//f.Write(http.responseText.replace(/[\r\n]+/g,"\n").replace(/^[\r\n]/g,""));
//http.open("GET", website="http://www.malwaredomainlist.com/hostslist/hosts.txt", false);
//http.setRequestHeader("Accept","text/html");
//http.send();
//list=http.responseText.replace(/#.*[\r\n]/g,"").replace(/.*(localhost|rapidshare|mediafire|hotfile).*/g,"").replace(/[\r\n]+/g,"\n");
//f.Write(list.replace(/127\.0\.0\.1[ \t]+/g,""));
//http.open("GET",website="https://spyeyetracker.abuse.ch/blocklist.php?download=domainblocklist",false);
//http.setRequestHeader("Accept","text/html");
//http.send();
//f.Write(http.responseText.replace(/[\r\n]#.*/g,"").replace(/.*$/,"").replace(/^#.*[\r\n]/g,"").replace(/[ \t]#.*[\r\n]/g,"\n"));
//http.open("GET",website="https://zeustracker.abuse.ch/blocklist.php?download=domainblocklist",false);
//http.setRequestHeader("Accept","text/html");
//http.send();
//f.Write(http.responseText.replace(/[\r\n]#.*/g,"").replace(/.*$/,"").replace(/^#.*[\r\n]/g,"").replace(/[ \t]#.*[\r\n]/g,"\n"));
//http.open("GET",website="http://amada.abuse.ch/blocklist.php?download=domainblocklist",false);
//http.setRequestHeader("Accept","text/html");
//http.send();
//f.Write(http.responseText.replace(/[\r\n]#.*/g,"").replace(/.*$/,"").replace(/^#.*[\r\n]/g,"").replace(/[ \t]#.*[\r\n]/g,"\n"));
//http.open("GET","http://dshield.org/feeds/suspiciousdomains_High.txt",false);
//http.setRequestHeader("Accept","text/html");
//http.send();
//f.Write(http.responseText.replace(/[\r\n]Site[\r\n]/g,"\n").replace(/[\r\n]#.*/g,"").replace(/\t?[\r\n]/g,"\n").replace(/^#.*[\r\n]/g,"").replace(/ #.*[\r\n]/g,"\n"));
f.Close();